


  ###all users
  
 GET http://localhost:8000/users

### insert users

POST http://localhost:8000/users
  Content-Type: application/json
  Accept: application/json

   {
    "name": "fiver",
    "email": "ghh@example.com",
    "password": "123456"
   
   
   }


###insert a new user
 POST http://localhost:8000/register
  Content-Type: application/json
  Accept: application/json

   {
    "userId": 1,
    "username": "zinadene",
   "password": "ddd"
   
   }





###
  POST http://localhost:8000/login
    Content-Type: application/json

    {    
        "username": "zinadene",
        "password": "ddd"
   

    }

###admin 
  GET http://localhost:8000/users/6
   Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBhYmxvIiwicm9sZSI6ImFkbWluIiwidXNlcklkIjo1LCJleHAiOjE3MTgxMTU3ODJ9.zdECR9BXHbkl88FhJK4YThAcXOFre8o_agsE10rmojs

### user//non admin
POST   http://localhost:8000/login
     Content-Type: application/json

    {
       "username": "zinadene",
   "password": "ddd"

    }

###user // non admin
GET http://localhost:8000/users/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InppbmFkZW5lIiwicm9sZSI6InVzZXIiLCJ1c2VySWQiOjYsImV4cCI6MTcxODEyMzAzMX0.z_xKKJ5rwKt0E8po-G0eqiPrkTr1L5ndIfUUCKQOVIE





### category
GET http://localhost:8000/category

### insert category

POST http://localhost:8000/category
Content-Type: application/json
Accept: application/json

{
     "name": "test2",
    "menu_item": "pizza"
}

### update category

PUT http://localhost:8000/category/
Content-Type: application/json
Accept: application/json

{
    "name": "test2",
    "menu_items": "pizza"
}

### delete category

DELETE http://localhost:8000/category/1







### get restraunts

GET http://localhost:8000/restraunts

###insert restraunt

POST http://localhost:8000/restraunts
Content-Type: application/json
Accept: application/json

{
        "name":"Kentucky",
        "street_address":"texas",
        "zip_code":345,
        "city_id":1
       
}
        




###update restraunt

PUT http://localhost:8000/restraunts
Content-Type: application/json
Accept: application/json

{


}

###delete restraunt

DELETE http://localhost:8000/restraunts/1






###get states

GET http://localhost:8000/state

###insert states

POST http://localhost:8000/state
Content-Type: application/json
Accept: application/json

{
  "id":10,
 "name":"Houston",
    "code":"TTD"
    

}

###update states

PUT http://localhost:8000/state
Content-Type: application/json
Accept: application/json

{
   "name":"houston",
    "code":3490,
    "city":"Mississipi"

}

###delete states

DELETE http://localhost:8000/state/1





### get orders

GET http://localhost:8000/Orders

###insert orders

POST http://localhost:8000/Orders
Content-Type: application/json
Accept: application/json

{
   "id":9,
  "restaurant_id":3,
  " estimated_delivery_time":null,
  "actual_delivery_time":null,
  "delivery_address_id":1,
  "user_id":3,
  "driver_id":4,
  "price":2790,
  "discount":90,
  "final_price":2700,
  "comment":"best",
  "created_at":null,
  "updated_at":null


}

###update Orders

PUT http://localhost:8000/Orders/
Content-Type: application/json
Accept: application/json

{
   
   "id":9,
  "restaurant_id":3,
  " estimated_delivery_time":null,
  "actual_delivery_time":7,
  "delivery_address_id":1,
  "user_id":3,
  "driver_id":4,
  "price":2790,
  "discount":90,
  "final_price":2700,
  "comment":"best",
  "created_at":"date",
  "updated_at":null


}

###delete Orders

DELETE http://localhost:8000/Orders/






### get address

GET http://localhost:8000/address/

###insert address

POST http://localhost:8000/address
Content-Type: application/json
Accept: application/json

{
        
        "street_address_2":"Kensas",
        "zip_code":50,
        "user_id":2,
        "city_id":1,
        "street_address_1":"kensas",
        "delivery_instructions":"On the first line",
        "user":"Morgan"


}
      




###update address

PUT http://localhost:8000/address/9
Content-Type: application/json
Accept: application/json

{
   "street_adddress_1":"Garissa"
      


}

###delete address

DELETE http://localhost:8000/address/







###get city

GET http://localhost:8000/city/

###insert city

POST http://localhost:8000/city
Content-Type: application/json
Accept: application/json

{
  "id": 9,
  "name":"Michigan",
  "state_id":2,
  "zip_code":23


}

###update city

PUT http://localhost:8000/city/2
Content-Type: application/json
Accept: application/json

{


}

###delete city

DELETE http://localhost:8000/city/







###get comment

GET http://localhost:8000/comment/

###insert comment

POST http://localhost:8000/comment
Content-Type: application/json
Accept: application/json

{
     "id":6,
     "order_id":1,
       "user_id":2,
        "comment_text":"good quality",
         "is_complaint":true,
         "is_praise":true


}

###update comment

PUT http://localhost:8000/comment
Content-Type: application/json
Accept: application/json

{


}

###delete comment

DELETE http://localhost:8000/comment/





###get menu_item

GET http://localhost:8000/menu_item/

###insert menu_item

POST http://localhost:8000/menu_item
Content-Type: application/json
Accept: application/json

{ 
     "id":9,
     
     "name":"Melody",
       "restaurant_id" :2,
        "category_id":6,
        "description":"deep Fry",
        "ingredients":"Raw Meet",
        "price":3899,
        "active":true
}

###update menu_item

PUT http://localhost:8000/menu_item
Content-Type: application/json
Accept: application/json

{

}

###delete menu_item

DELETE http://localhost:8000/menu_item/







### get Orderstatus

GET http://localhost:8000/OrderStatus/

###insert Orderstatus

POST http://localhost:8000/OrderStatus
Content-Type: application/json
Accept: application/json




###update Orderstatus

PUT http://localhost:8000/OrderStatus
Content-Type: application/json
Accept: application/json

{

}

###delete Orderstatus

DELETE http://localhost:8000/OrderStatus/






### get restrauntowner

GET http://localhost:8000/restrauntowner/

###insert restrauntowner

POST http://localhost:8000/restrauntowner
Content-Type: application/json
Accept: application/json

{

}

###update restrauntowner

PUT http://localhost:8000/restrauntowner
Content-Type: application/json
Accept: application/json

{

}

###delete restrauntowner

DELETE http://localhost:8000/restrauntowner/





###  get StatusCatalog

GET http://localhost:8000/StatusCatalog/

###insert StatusCatalog

POST http://localhost:8000/StatusCatalog
Content-Type: application/json
Accept: application/json

{
  "id":9,
  "name":"Delivered",
  "order_status_id":9,
  "order_menu_item_id":9,
  "order_id":2,
  "user_id":1

}

###update StatusCatalog

PUT http://localhost:8000/StatusCatalog
Content-Type: application/json
Accept: application/json

{

}

###delete StatusCatalog

DELETE http://localhost:8000/StatusCatalog/







### get OrderMenuItem

GET http://localhost:8000/orderMenuItem/

###insert OrderMenuItem

POST http://localhost:8000/orderMenuItem
Content-Type: application/json
Accept: application/json

{

}

###update OrderMenuItem

PUT http://localhost:8000/orderMenuItem
Content-Type: application/json
Accept: application/json

{

}

###delete OrderMenuItem

DELETE http://localhost:8000/orderMenuItem/




